package ultasun.csg.gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.Timer;

/**
 *
 * @author ultasun
 */
public class JcsgWaitWindow extends javax.swing.JFrame {
    private final Timer t;
    private final String verb;
    private int counter;

    public JcsgWaitWindow(String verb) {
        initComponents();
        this.verb = verb + "... ";
        this.counter = 0;
        this.jLabel1.setText(this.verb + counter);
        this.t = new Timer(1000, new JWaitWindowActionListener(this));
        this.setTitle(verb);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setAlwaysOnTop(true);
    }

    public void incrementLabel() {
        counter++;
        jLabel1.setText(verb + counter);
    }

    @Override
    public void setVisible(boolean visible) {
        super.setVisible(visible);
        if (visible) {
            this.t.start();
        } else {
            this.t.stop();
        }
    }

    @Override
    public void dispose() {
        super.dispose();
        this.t.stop();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    private class JWaitWindowActionListener implements ActionListener {
        private final JcsgWaitWindow jww;

        public JWaitWindowActionListener(JcsgWaitWindow jww) {
            this.jww = jww;
        }

        @Override
        public void actionPerformed(ActionEvent ae) {
            jww.incrementLabel();
        }

    }
}
